# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'WIPReact' do
  pod 'Google/SignIn'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'TwitterCore'
  pod 'TwitterKit'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'react-native-geocoder', :path => '../node_modules/react-native-geocoder'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
