# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'WIPReact' do
 pod 'Firebase/Core'
 pod 'Firebase/Auth'
 pod 'Firebase/Firestore'
 pod 'TwitterCore'
 pod 'TwitterKit'

end
